[project]
name = "art-rl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=0.3.72",
    "openpipe-art>=0.4.4",
    "weave>=0.51.56",
    "openpipe-ard[backend]>=0.4.4",
]
